/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-112691-gf9fdaa2ca9-20231105"
#endif /* AVUTIL_FFVERSION_H */
